### Taller 2b: Matriz Inversa y Descomposición LU
**Nombre:** Lindsay Guzmán

### Código modificado para Obtener Matriz inversa 

In [307]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [308]:
# ----------------------------- logging --------------------------
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

import numpy as np


[01-13 21:57:52][INFO] 2026-01-13 21:57:52.417737


In [309]:
%autoreload 2
from src import eliminacion_gaussiana

***Ejemplo:***

In [310]:
A = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

In [311]:
import numpy as np


# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    # for i in range(n - 2, -1, -1):
    #     suma = 0
    #     for j in range(i + 1, n):
    #         suma += A[i, j] * solucion[j]
    #     solucion[i] = (A[i, n] - suma) / A[i, i]

    return A


In [312]:
from pprint import pprint

pprint(A)
gauss_jordan(A)

[[1, 3, 4], [2, 1, 3], [4, 2, 1]]
[01-13 21:57:52][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:57:52][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 21:57:52][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

***Concatenar Matrices/ poner matriz identidad a la derecha***

In [313]:
n = len(A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[1., 3., 4., 1., 0., 0.],
       [2., 1., 3., 0., 1., 0.],
       [4., 2., 1., 0., 0., 1.]])

***Matriz Inversa***

In [314]:
m_inv = gauss_jordan(A_aug)
m_inv

[01-13 21:57:52][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 21:57:52][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 21:57:52][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]


array([[ 1. ,  0. ,  0. , -0.2,  0.2,  0.2],
       [-0. ,  1. ,  0. ,  0.4, -0.6,  0.2],
       [-0. , -0. ,  1. , -0. ,  0.4, -0.2]])

In [315]:
m_inv[:, n:]

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

### **Comprobación:**

In [316]:
np.linalg.inv(np.array(A))

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [ 0. ,  0.4, -0.2]])

**1. Encontrar la matriz inversa para la siguientes matrices:**<br>


### **Ejercicios**

 1. Matriz $A_1$ <br>
$A_1$=
\begin{bmatrix}
1 & 3 & 4\\
2 & 1 & 3\\
4 & 2 & 1
\end{bmatrix}

In [317]:
A_1 = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

gauss_jordan(A_1)

n = len(A_1)
A1_aug = np.hstack((A_1, np.eye(n)))
A1_aug
a1_inv = gauss_jordan(A1_aug)
a1_inv
print("Matriz Inversa:")

a1_inv[:, n:]

[01-13 21:57:52][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:57:52][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 21:57:52][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[01-13 21:57:52][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 21:57:52][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 21:57:52][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]
Matriz Inversa:


array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

***Comprobación***

In [318]:
np.linalg.inv(np.array(A_1))

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [ 0. ,  0.4, -0.2]])

2. Matriz $A_2$


$A_2$=
\begin{bmatrix}
1 & 2 & 3\\
0 & 1 & 4\\
5 & 6 & 0
\end{bmatrix}


In [319]:
A_2 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

gauss_jordan(A_2)

n = len(A_2)
A2_aug = np.hstack((A_2, np.eye(n)))
A2_aug
a2_inv = gauss_jordan(A2_aug)
a2_inv
print("Matriz Inversa:")

a2_inv[:, n:]

[01-13 21:57:52][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 21:57:52][INFO] 
[[ 1.  0. -5.]
 [ 0.  1.  4.]
 [ 0.  0.  1.]]
[01-13 21:57:52][INFO] 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[01-13 21:57:52][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 21:57:52][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 21:57:52][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]
Matriz Inversa:


array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

***Comprobación***

In [320]:
np.linalg.inv(np.array(A_2))

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

3. Matriz $A_3$

$A_3$=
\begin{bmatrix}
4 & 2 & 1\\
2 & 1 & 3\\
1 & 3 & 4
\end{bmatrix}


In [321]:
A_3 = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]

gauss_jordan(A_3)

n = len(A_3)
A3_aug = np.hstack((A_3, np.eye(n)))
A3_aug
a3_inv = gauss_jordan(A3_aug)
a3_inv
print("Matriz Inversa:")

a3_inv[:, n:]

[01-13 21:57:52][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:57:52][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 21:57:52][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[01-13 21:57:52][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 21:57:52][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [-0.   1.   1.  -0.  -0.2  0.4]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 21:57:52][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]
Matriz Inversa:


array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4, -0. ]])

***Comprobación***

In [322]:
np.linalg.inv(np.array(A_3))

array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4,  0. ]])

4. Matriz $A_4$

$A_4$=
\begin{bmatrix}
2 & 4 & 6 & 1\\
4 & 7 & 5 & -6\\
2 & 5 & 18 & 10\\
6 & 12 & 38 & 16
\end{bmatrix}



In [323]:
A_4 = [[2, 4, 6, 1], [4, 7, 5, -6], [2, 5, 18, 10], [6, 12, 38, 16]]

gauss_jordan(A_4)

n = len(A_4)
A4_aug = np.hstack((A_4, np.eye(n)))
A4_aug
a4_inv = gauss_jordan(A4_aug)
a4_inv
print("Matriz Inversa:")

a4_inv[:, n:]

[01-13 21:57:52][INFO] 
[[ 1.   2.   3.   0.5]
 [ 0.  -1.  -7.  -8. ]
 [ 0.   1.  12.   9. ]
 [ 0.   0.  20.  13. ]]
[01-13 21:57:52][INFO] 
[[  1.    0.  -11.  -15.5]
 [ -0.    1.    7.    8. ]
 [  0.    0.    5.    1. ]
 [  0.    0.   20.   13. ]]
[01-13 21:57:52][INFO] 
[[  1.    0.    0.  -13.3]
 [ -0.    1.    0.    6.6]
 [  0.    0.    1.    0.2]
 [  0.    0.    0.    9. ]]
[01-13 21:57:52][INFO] 
[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[01-13 21:57:52][INFO] 
[[ 1.   2.   3.   0.5  0.5  0.   0.   0. ]
 [ 0.  -1.  -7.  -8.  -2.   1.   0.   0. ]
 [ 0.   1.  12.   9.  -1.   0.   1.   0. ]
 [ 0.   0.  20.  13.  -3.   0.   0.   1. ]]
[01-13 21:57:52][INFO] 
[[  1.    0.  -11.  -15.5  -3.5   2.    0.    0. ]
 [ -0.    1.    7.    8.    2.   -1.   -0.   -0. ]
 [  0.    0.    5.    1.   -3.    1.    1.    0. ]
 [  0.    0.   20.   13.   -3.    0.    0.    1. ]]
[01-13 21:57:52][INFO] 
[[  1.    0.    0.  -13.3 -10.1   4.2   2.2   0. ]
 [ -0.    1.   

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

***Comprobación***

In [324]:
np.linalg.inv(np.array(A_4))

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

**2.Calcule la descomposición LU para estas matrices y encuentre la solución para estos vectores de valores independientes b.**

### Ejercicio 1

In [325]:
from src import (
    descomposicion_LU,
    resolver_LU,
    matriz_aumentada,
    separar_m_aumentada,
)
L, U = descomposicion_LU(A_1)

b1 = [1, 2, 4]
x1 = resolver_LU(L, U, b1)
print("Solucion x1 =\n", x)

[01-13 21:57:52][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:57:52][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 21:57:52][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 21:57:52][INFO] Sustitución hacia adelante
[01-13 21:57:52][INFO] y = 
[[1.]
 [0.]
 [0.]]
[01-13 21:57:52][INFO] Sustitución hacia atrás
[01-13 21:57:52][INFO] i = 1
[01-13 21:57:52][INFO] suma = [0.]
[01-13 21:57:52][INFO] U[i, i] = -5.0
[01-13 21:57:52][INFO] y[i] = [0.]
[01-13 21:57:52][INFO] i = 0
[01-13 21:57:52][INFO] suma = [0.]
[01-13 21:57:52][INFO] U[i, i] = 1.0
[01-13 21:57:52][INFO] y[i] = [1.]
Solucion x1 =
 [[ 1.]
 [-0.]
 [-0.]]


## Ejercicio 2

In [326]:
L, U = descomposicion_LU(A_2)

b2 = [3, -5, 2]
x2 = resolver_LU(L, U, b2)
print("Solucion x2 =\n", x2)

[01-13 21:57:52][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 21:57:52][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 21:57:52][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 21:57:52][INFO] Sustitución hacia adelante
[01-13 21:57:52][INFO] y = 
[[  3.]
 [ -5.]
 [-33.]]
[01-13 21:57:52][INFO] Sustitución hacia atrás
[01-13 21:57:52][INFO] i = 1
[01-13 21:57:52][INFO] suma = [-132.]
[01-13 21:57:52][INFO] U[i, i] = 1.0
[01-13 21:57:52][INFO] y[i] = [-5.]
[01-13 21:57:52][INFO] i = 0
[01-13 21:57:52][INFO] suma = [155.]
[01-13 21:57:52][INFO] U[i, i] = 1.0
[01-13 21:57:52][INFO] y[i] = [3.]
Solucion x2 =
 [[-152.]
 [ 127.]
 [ -33.]]


## Ejercicio 3

In [327]:
L, U = descomposicion_LU(A_3)

b3 = [7, 8, -1]
x3 = resolver_LU(L, U, b3)


[01-13 21:57:53][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

## Ejercicio 4

In [ ]:
L, U = descomposicion_LU(A_4)

b4 = [1, 2, 4, 5]
x4 = resolver_LU(L, U, b4)
print("Solucion x4 =\n", x4)

[01-13 21:52:37][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 21:52:37][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 21:52:37][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:52:37][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:52:37][INFO] Sustitución hacia adelante
[01-13 21:52:37][INFO] y = 
[[  1.]
 [  0.]
 [  3.]
 [-10.]]
[01-13 21:52:37][INFO] Sustitución hacia atrás
[01-13 21:52:37][INFO] i = 2
[01-13 21:52:37][INFO] suma = [-1.11111111]
[01-13 21:52:37][INFO] U[i, i] = 5.0
[01-13 21:52:37][INFO] y[i] = [3.]
[01-13 21:52:37][INFO] i = 1
[01-13 21:52:37][INFO] suma = [3.13333333]
[01-13 21:52:37][INFO] U[i, i] = -1.0
[01-13 21:52:37][INFO] y[i] = [0.]
[01-13 21:52:37][INFO] i = 0
[01-13 21:52:37][INFO] suma = [16.35555556]
[01-13 21:52:37][INFO] U[i, i] = 2.0
[01-13 21:52:37][INFO] y[i] = [1.]
Sol

## Ejercicio 5

In [ ]:
L, U = descomposicion_LU(A_4)

b5 = [3, -5, 2, 6]
x5 = resolver_LU(L, U, b5)
print("Solucion x5 =\n", x5)

[01-13 21:56:05][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 21:56:05][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 21:56:05][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]


[01-13 21:56:06][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:56:06][INFO] Sustitución hacia adelante
[01-13 21:56:06][INFO] y = 
[[  3.]
 [-11.]
 [-12.]
 [ 45.]]
[01-13 21:56:06][INFO] Sustitución hacia atrás
[01-13 21:56:06][INFO] i = 2
[01-13 21:56:06][INFO] suma = [5.]
[01-13 21:56:06][INFO] U[i, i] = 5.0
[01-13 21:56:06][INFO] y[i] = [-12.]
[01-13 21:56:06][INFO] i = 1
[01-13 21:56:06][INFO] suma = [-16.2]
[01-13 21:56:06][INFO] U[i, i] = -1.0
[01-13 21:56:06][INFO] y[i] = [-11.]
[01-13 21:56:06][INFO] i = 0
[01-13 21:56:06][INFO] suma = [-36.2]
[01-13 21:56:06][INFO] U[i, i] = 2.0
[01-13 21:56:06][INFO] y[i] = [3.]
Solucion x5 =
 [[19.6]
 [-5.2]
 [-3.4]
 [ 5. ]]


## Ejercicio 6

In [ ]:
L, U = descomposicion_LU(A_4)

b6 = [3, -5, 2, 6]
x6 = resolver_LU(L, U, b6)
print("Solucion x6 =\n", x6)

[01-13 21:55:59][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 21:55:59][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 21:55:59][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:55:59][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:55:59][INFO] Sustitución hacia adelante
[01-13 21:55:59][INFO] y = 
[[  3.]
 [-11.]
 [-12.]
 [ 45.]]
[01-13 21:55:59][INFO] Sustitución hacia atrás
[01-13 21:55:59][INFO] i = 2
[01-13 21:55:59][INFO] suma = [5.]
[01-13 21:55:59][INFO] U[i, i] = 5.0
[01-13 21:55:59][INFO] y[i] = [-12.]
[01-13 21:55:59][INFO] i = 1
[01-13 21:55:59][INFO] suma = [-16.2]
[01-13 21:55:59][INFO] U[i, i] = -1.0
[01-13 21:55:59][INFO] y[i] = [-11.]
[01-13 21:55:59][INFO] i = 0
[01-13 21:55:59][INFO] suma = [-36.2]
[01-13 21:55:59][INFO] U[i, i] = 2.0
[01-13 21:55:59][INFO] y[i] = [3.]
Solucion x6 =
 [[19

## Ejercicio 7

In [ ]:
L, U = descomposicion_LU(A_4)

b7 = [7, 8, -1, 0]
x7 = resolver_LU(L, U, b7)
print("Solucion x7 =\n", x7)

[01-13 21:55:43][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 21:55:43][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 21:55:43][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:55:43][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 21:55:43][INFO] Sustitución hacia adelante
[01-13 21:55:43][INFO] y = 
[[  7.]
 [ -6.]
 [-14.]
 [ 35.]]
[01-13 21:55:43][INFO] Sustitución hacia atrás
[01-13 21:55:43][INFO] i = 2


[01-13 21:55:43][INFO] suma = [3.88888889]
[01-13 21:55:43][INFO] U[i, i] = 5.0
[01-13 21:55:43][INFO] y[i] = [-14.]
[01-13 21:55:43][INFO] i = 1
[01-13 21:55:43][INFO] suma = [-6.06666667]
[01-13 21:55:43][INFO] U[i, i] = -1.0
[01-13 21:55:43][INFO] y[i] = [-6.]
[01-13 21:55:43][INFO] i = 0
[01-13 21:55:43][INFO] suma = [-17.84444444]
[01-13 21:55:43][INFO] U[i, i] = 2.0
[01-13 21:55:43][INFO] y[i] = [7.]
Solucion x7 =
 [[12.42222222]
 [-0.06666667]
 [-3.57777778]
 [ 3.88888889]]
