### Taller 2b: Matriz Inversa y Descomposición LU
**Nombre:** Lindsay Guzmán

### Código modificado para Obtener Matriz inversa 

In [151]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [152]:
# ----------------------------- logging --------------------------
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

import numpy as np


[01-13 21:27:03][INFO] 2026-01-13 21:27:03.933191


In [153]:
%autoreload 2
from src import eliminacion_gaussiana

***Ejemplo:***

In [154]:
A = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

In [155]:
import numpy as np


# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    # for i in range(n - 2, -1, -1):
    #     suma = 0
    #     for j in range(i + 1, n):
    #         suma += A[i, j] * solucion[j]
    #     solucion[i] = (A[i, n] - suma) / A[i, i]

    return A


In [156]:
from pprint import pprint

pprint(A)
gauss_jordan(A)

[[1, 3, 4], [2, 1, 3], [4, 2, 1]]
[01-13 21:27:04][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:27:04][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 21:27:04][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

***Concatenar Matrices/ poner matriz identidad a la derecha***

In [157]:
n = len(A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[1., 3., 4., 1., 0., 0.],
       [2., 1., 3., 0., 1., 0.],
       [4., 2., 1., 0., 0., 1.]])

***Matriz Inversa***

In [158]:
m_inv = gauss_jordan(A_aug)
m_inv

[01-13 21:27:04][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 21:27:04][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]


[01-13 21:27:04][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]


array([[ 1. ,  0. ,  0. , -0.2,  0.2,  0.2],
       [-0. ,  1. ,  0. ,  0.4, -0.6,  0.2],
       [-0. , -0. ,  1. , -0. ,  0.4, -0.2]])

In [159]:
m_inv[:, n:]

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

### **Comprobación:**

In [160]:
np.linalg.inv(np.array(A))

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [ 0. ,  0.4, -0.2]])

**1. Encontrar la matriz inversa para la siguientes matrices:**<br>


### **Ejercicios**

 1. Matriz $A_1$ <br>
$A_1$=
\begin{bmatrix}
1 & 3 & 4\\
2 & 1 & 3\\
4 & 2 & 1
\end{bmatrix}

In [161]:
A_1 = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

gauss_jordan(A_1)

n = len(A_1)
A1_aug = np.hstack((A_1, np.eye(n)))
A1_aug
a1_inv = gauss_jordan(A1_aug)
a1_inv
print("Matriz Inversa:")

a1_inv[:, n:]

[01-13 21:27:04][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:27:04][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 21:27:04][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[01-13 21:27:04][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 21:27:04][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 21:27:04][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]
Matriz Inversa:


array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

***Comprobación***

In [162]:
np.linalg.inv(np.array(A_1))

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [ 0. ,  0.4, -0.2]])

2. Matriz $A_2$


$A_2$=
\begin{bmatrix}
1 & 2 & 3\\
0 & 1 & 4\\
5 & 6 & 0
\end{bmatrix}


In [163]:
A_2 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

gauss_jordan(A_2)

n = len(A_2)
A2_aug = np.hstack((A_2, np.eye(n)))
A2_aug
a2_inv = gauss_jordan(A2_aug)
a2_inv
print("Matriz Inversa:")

a2_inv[:, n:]

[01-13 21:27:04][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 21:27:04][INFO] 
[[ 1.  0. -5.]
 [ 0.  1.  4.]
 [ 0.  0.  1.]]
[01-13 21:27:04][INFO] 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[01-13 21:27:04][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 21:27:04][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 21:27:04][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]
Matriz Inversa:


array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

***Comprobación***

In [164]:
np.linalg.inv(np.array(A_2))

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

3. Matriz $A_3$

$A_3$=
\begin{bmatrix}
4 & 2 & 1\\
2 & 1 & 3\\
1 & 3 & 4
\end{bmatrix}


In [165]:
A_3 = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]

gauss_jordan(A_3)

n = len(A_3)
A3_aug = np.hstack((A_3, np.eye(n)))
A3_aug
a3_inv = gauss_jordan(A3_aug)
a3_inv
print("Matriz Inversa:")

a3_inv[:, n:]

[01-13 21:27:04][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 21:27:04][INFO] 
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0. -5.]]
[01-13 21:27:04][INFO] 
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
[01-13 21:27:04][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 21:27:04][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [-0.   1.   1.  -0.  -0.2  0.4]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 21:27:04][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]
Matriz Inversa:


array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4, -0. ]])

***Comprobación***

In [166]:
np.linalg.inv(np.array(A_3))

array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4,  0. ]])

4. Matriz $A_4$

$A_4$=
\begin{bmatrix}
2 & 4 & 6 & 1\\
4 & 7 & 5 & -6\\
2 & 5 & 18 & 10\\
6 & 12 & 38 & 16
\end{bmatrix}



In [169]:
A_4 = [[2, 4, 6, 1], [4, 7, 5, -6], [2, 5, 18, 10], [6, 12, 38, 16]]

gauss_jordan(A_4)

n = len(A_4)
A4_aug = np.hstack((A_4, np.eye(n)))
A4_aug
a4_inv = gauss_jordan(A4_aug)
a4_inv
print("Matriz Inversa:")

a4_inv[:, n:]

[01-13 21:29:46][INFO] 
[[ 1.   2.   3.   0.5]
 [ 0.  -1.  -7.  -8. ]
 [ 0.   1.  12.   9. ]
 [ 0.   0.  20.  13. ]]


[01-13 21:29:46][INFO] 
[[  1.    0.  -11.  -15.5]
 [ -0.    1.    7.    8. ]
 [  0.    0.    5.    1. ]
 [  0.    0.   20.   13. ]]
[01-13 21:29:46][INFO] 
[[  1.    0.    0.  -13.3]
 [ -0.    1.    0.    6.6]
 [  0.    0.    1.    0.2]
 [  0.    0.    0.    9. ]]
[01-13 21:29:46][INFO] 
[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[01-13 21:29:46][INFO] 
[[ 1.   2.   3.   0.5  0.5  0.   0.   0. ]
 [ 0.  -1.  -7.  -8.  -2.   1.   0.   0. ]
 [ 0.   1.  12.   9.  -1.   0.   1.   0. ]
 [ 0.   0.  20.  13.  -3.   0.   0.   1. ]]
[01-13 21:29:46][INFO] 
[[  1.    0.  -11.  -15.5  -3.5   2.    0.    0. ]
 [ -0.    1.    7.    8.    2.   -1.   -0.   -0. ]
 [  0.    0.    5.    1.   -3.    1.    1.    0. ]
 [  0.    0.   20.   13.   -3.    0.    0.    1. ]]
[01-13 21:29:46][INFO] 
[[  1.    0.    0.  -13.3 -10.1   4.2   2.2   0. ]
 [ -0.    1.    0.    6.6   6.2  -2.4  -1.4  -0. ]
 [  0.    0.    1.    0.2  -0.6   0.2   0.2   0. ]
 [  0.    0.    0.    9.    9.

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

***Comprobación***

In [170]:
np.linalg.inv(np.array(A_4))

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

2. 